import Footer from "@/components/footer/indxe";
import Navbar04Page from "@/components/navbar/navbar-04";
import type { Metadata } from "next";
import { Bricolage_Grotesque, Raleway } from "next/font/google";
import "./globals.css";

const bricolage =Bricolage_Grotesque({

  variable: "--font-bricolage",
  subsets: ["latin"],
  display: "swap",
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${raleway.variable} ${bricolage.variable} antialiased font-raleway`}
      >
        <Navbar04Page/>
      <div className="min-h-screen">
      {children}
      </div>
        <Footer/>
      </body>
    </html>
  );
}
